/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD016 Aunt p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD016 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD016 Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD057 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD057 Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD063 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD063 Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD065 Aunt p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD065 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
#/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD066_C1 Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
#/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD066_C1 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD073_C1full Aunt1 p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD073_C1full Aunt2 p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD073_C1full Aunt3 p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD073_C1full Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD073_C1full Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD077_C1to4 Aunt p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD077_C1to4 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD081_C1_2 Aunt1 p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD081_C1_2 Aunt2 p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD081_C1_2 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD081_C1_2 Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD090 Aunt p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD090 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD094 Aunt p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD094 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD105_C1full Aunt p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD105_C1full Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD105_C1full Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD116_C1C2 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD116_C1C2 Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD117 Grandparents p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R
/cm/shared/apps/R/3.2.4/bin/R --vanilla --slave --args PGD117 Uncle p1 'E*_Bl*' /uz/data/avalok/symbiosys/gcpi_r_kul_joris_vermeesch/jding/PGD/ < /home/jding0/siCHILD_toGC/siCHILD_core.R

